[versions]
androidGradlePlugin = "7.4.2"
kotlin = "1.7.0"

androidxLifecycle = "2.5.0-beta01"
androidxNavigation = "2.4.1"

hilt = "2.46.1"

material = "1.7.0-alpha02"

[libraries]
coroutines-android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.1"

androidx-appcompat = "androidx.appcompat:appcompat:1.4.1"
androidx-activity = "androidx.activity:activity-ktx:1.7.2"
androidx-fragment = "androidx.fragment:fragment-ktx:1.4.1"
androidx-core = "androidx.core:core-ktx:1.10.1"
androidx-core-splashscreen = "androidx.core:core-splashscreen:1.0.1"
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.3.0"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
androidx-preference = "androidx.preference:preference:1.2.0"
androidx-profileinstaller = "androidx.profileinstaller:profileinstaller:1.3.1"

androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxLifecycle" }

androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidxNavigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidxNavigation" }

dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
dagger-hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }

androidx-test-runner = "androidx.test:runner:1.5.2"
androidx-test-junit = "androidx.test.ext:junit:1.1.5"

material = { module = "com.google.android.material:material", version.ref = "material" }
flexbox = "com.google.android.flexbox:flexbox:3.0.0"

insetter = "dev.chrisbanes.insetter:insetter:0.6.1"

play-core = "com.google.android.play:core:1.10.3"
play-core-ktx = "com.google.android.play:core-ktx:1.8.1"

licenses = "com.google.android.gms:play-services-oss-licenses:17.0.1"

junit = "junit:junit:4.13.2"
robolectric = "org.robolectric:robolectric:4.10.3"

[plugins]
androidGradlePlugin = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlinPlugin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hiltPlugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
