name: Code Format Suggester
on: [pull_request]
jobs:
  code-format-suggest:
    if: github.head_ref != 'develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu
          cache: gradle
      - run: ./gradlew spotlessKotlinApply
      - uses: reviewdog/action-suggester@v1.5.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: spotless